### ISSUE TITLE
Fix crash-7dbfd995

### ISSUE THREAD

**Issue by m4drat** [m4drat/memplusplus#88]

**Comment by m4drat** [comment]
```
    #0 0x559832a19d34 in mpp::Chunk::GetSize() const /home/madrat/memplusplus/libmemplusplus/include/mpplib/chunk.hpp:148:39
    #1 0x559832a68870 in mpp::Heuristics::LayoutGeneralGraph(std::unique_ptr<mpp::GcGraph, std::function<void (mpp::GcGraph*)> >&) /home/madrat/memplusplus/libmemplusplus/src/heuristics/heuristics.cpp:19:59
    #2 0x559832a6ad7a in mpp::Heuristics::LayoutHeap() /home/madrat/memplusplus/libmemplusplus/src/heuristics/heuristics.cpp:76:45
    #3 0x559832a32a82 in mpp::GarbageCollector::Collect() /home/madrat/memplusplus/libmemplusplus/src/gc.cpp:107:61
```

```
❓  DBG: /home/madrat/memplusplus/fuzzer/src/fuzzer_main.cpp:87 > CreateVertex(0)                                                                                                                                                                                                                                              ❓  DBG: /home/madrat/memplusplus/fuzzer/src/fuzzer_main.cpp:87 > CreateVertex(1)
❓  DBG: /home/madrat/memplusplus/fuzzer/src/fuzzer_main.cpp:106 > CreateEdge(0, 0, 0)
❓  DBG: /home/madrat/memplusplus/fuzzer/src/fuzzer_main.cpp:106 > CreateEdge(1, 0, 0)
❓  DBG: /home/madrat/memplusplus/fuzzer/src/fuzzer_main.cpp:145 > CollectGarbage()
❓  DBG: /home/madrat/memplusplus/fuzzer/src/fuzzer_main.cpp:145 > CollectGarbage()
-> CRASH!
```
